// Regenerates supabase/functions/ask-cv/cv.ts from resume.md, the single source of truth.
// Usage: node scripts/sync-cv.mjs   (then redeploy the ask-cv function)
import { readFileSync, writeFileSync } from "node:fs";

const md = readFileSync(new URL("../resume.md", import.meta.url), "utf8");
const out = new URL("../supabase/functions/ask-cv/cv.ts", import.meta.url);
writeFileSync(out, `// Generated by scripts/sync-cv.mjs from resume.md — do not edit by hand.\nexport const CV = ${JSON.stringify(md)};\n`);
console.log(`cv.ts updated (${md.length} chars)`);
